### ISSUE TITLE
Import statement in Datasets format conversion.ipynb results in error

### ISSUE THREAD

**Issue by AJnsm** [imsb-uke/scGAN#10]
`import scanpy.api as sc`

resulted in the error 

`ImportError: cannot import name 'stacked_violin'`

Changing that line to 

`import scanpy as sc`

solved the problem, and the conversion works fine. 

This is something the people behind scanpy also suggest: https://github.com/theislab/scanpy/issues/1397

**Comment by fhausmann** [comment]
Hello and sorry for the late reply, 

The scanpy API was changed from `scanpy.api` to just `scanpy` in versions > 1.6. Since scGAN depends on scanpy 1.2.2 as written in the requirements.
Since there was also a change in the anndate format (used by scanpy to save the files), which does not work together with the current scGAN implementation, I would recommend you to run all code with scanpy==1.2.2. 
Please tell me, if that works for you or if there are any further issues.
