### ISSUE TITLE
Error when writing 'tf_records' using docker file

### ISSUE THREAD

**Issue by KOD1S** [imsb-uke/scGAN#19]
Hi, I have run the main.py file with parameters from the docker file but am receiving the below error message:

![Screenshot from 2022-06-13 14-25-33](https://user-images.githubusercontent.com/63750985/173373615-c0c4656f-d549-49ef-a204-63a43985cf83.png)

We are running on a GPU node on a HPC cluster. We have also tried without the docker file but the versions listed in the requirements file conflict with each other.

**Comment by fhausmann** [comment]
Hello @KOD1S,
the issue is related to an h5ad file which was written by a new version of anndata, which is not supported by scGAN. The issue is reported [here](https://github.com/scverse/anndata/issues/287) already.

Regarding the build without a Dockerfile, I would not recommend it, because the python version is rather old and therefore sometimes difficult do to build. The Dockerfile also reads the requirements from the requirements file, so there should not be any conflicting version. If you want, I can still have a look, but I would need some sort of error message for this.
