### ISSUE TITLE
Something wrong with multiprocessing when executing the training step

### ISSUE THREAD

**Issue by duohongrui** [imsb-uke/scGAN#20]
Hi, scGAN is very uesful for my research. No error occurred when I preprocessed the dataset but there was a problem when I was  performing the training step.
![image](https://user-images.githubusercontent.com/68155800/178765333-326b32bc-8714-4ff8-8424-2bc6737b53d1.png)
Could you please help me solve this problem? Is there something wrong with the parameters.json file?
Thanks very much!

**Comment by fhausmann** [comment]
Hello @duohongrui ,
I guess the issue is that the GPU is not specified as a list. You can have a look [here](https://github.com/imsb-uke/scGAN/blob/988ad959a94b90f09c2e5ac3da22045119afb87b/parameters.json#L4-L6).
If this don't solve it for you, could you send me the `parameters.json` to debug the issue ?

**Comment by duohongrui** [comment]
OK, thanks again for helping me solve the problem. I have sent the parameters.json file and h5ad data to you by email. Please check it.
I just altered the `experiments_dir`, `GPU`, `min_cells`, `min_genes`, `res`, `name_your_experiment` and `raw_input` in the json file.

**Comment by duohongrui** [comment]
Hi, @fhausmann. I tried your suggestions and tested the process again and the error was solved.
Thanks for your help!
