### ISSUE TITLE
It does not run when I use training mode

### ISSUE THREAD

**Issue by Layne-Huang** [imsb-uke/scGAN#24]
Hi,

I found that the code stopped without any error information or warning information when I run the training mode.

I also found that the code stopped at gan_model = cscGAN().

Could you please help me solve it?

**Comment by fhausmann** [comment]
Hey,
I would guess that this is related to memory usage since in that function the model is initialized, but it is hard to debug just from this information.
On what machine  (How much RAM, what GPU?)  are you trying to run cscGAN? 
Could you also check your memory usage while running? e.g. using `top` or `htop` .
