### ISSUE TITLE
Environment problem :(

### ISSUE THREAD

**Issue by DongShengze** [imsb-uke/scGAN#25]
Hi, when I just create an environment by python3.5 and try to install the requirements.txt, using
**pip install -r requirements.txt**
Here comes the error: 
**ERROR: Could not find a version that satisfies the requirement pygobject==3.20.0
ERROR: No matching distribution found for pygobject==3.20.0**
Btw, I am trying to run ur project on windows, would that work or it must be run on a linux system?

**Comment by fhausmann** [comment]
Hey,
Unfortunately, the mentioned `pygobject` version was removed from PyPi but it is probably not needed to run the code anyway.
I removed this and some others in 151a7f2 and installing the requirements works for me now again. Let me know, if there are any further problems.

Regarding running it on Windows, I'm not sure but I think it only works out of the box for Linux systems due to the old Tensorflow version and the requirement for GPU access. Sorry for that. It might be easier to use the pre-build docker image there (since all Python code & requirements are already installed) and you can find some information for docker & GPU for example here: https://stackoverflow.com/questions/49589229/is-gpu-pass-through-possible-with-docker-for-windows
However, we cannot provide any further help in supporting Windows for now.

**Comment by DongShengze** [comment]
I see, ty for the reply.

**Comment by pierremac** [comment]
I haven't tried any of it but as @fhausmann mentioned, Docker should be an option to run scGAN on Windows.
Otherwise I think the Windows Subsystem for Linux (WSL) should also do the trick.
In general, I found there are quite a few use cases where python code was not running natively on Windows but does on WSL.
And it should also support CUDA.
https://learn.microsoft.com/en-gb/windows/ai/directml/gpu-cuda-in-wsl
