### ISSUE TITLE
Assistance Needed with cscGAN Training Error

### ISSUE THREAD

**Issue by Xinle-Deng** [imsb-uke/scGAN#26]
Firstly, I want to commend you on the wonderful work you have done. I am very interested in scGAN and its applications. I have my own anndata with predefined clusters, so there is no need for additional clustering. The cluster information is stored in adata.obs['cluster'], where each element's data type is a pandas category, consistent with the outputs of sc.tl.louvain.

However, when I attempt to train cscGAN, I encounter the following error messages:
![image](https://github.com/imsb-uke/scGAN/assets/109469322/4f84d53f-716f-4ec2-b14c-5f73854b183e)

Could you please provide guidance on how to resolve this issue?

**Comment by fhausmann** [comment]
Hello @Xinle-Deng,

The issue is that your clusters (named `cluster_int` in our code) are not saved in the TFRecord files. If you want to use the code with your clusters, you must pass `cluster=<your clusters as integers per cell>, categories=<cell type names matching your cluster numbers>` into the  [`make_example`](https://github.com/imsb-uke/scGAN/blob/151a7f2f578625ca42fc5205208fce86bcb055b1/preprocessing/write_tfrecords.py#L40C5-L41C17) function.

I assume you already modified the `main.py` and did something like this, right? Could you let me know what modifications you did already if your problem persists after the modification to the `make_example` call mentioned above?

**Comment by Xinle-Deng** [comment]
> Hello @Xinle-Deng,
> 
> The issue is that your clusters (named `cluster_int` in our code) are not saved in the TFRecord files. If you want to use the code with your clusters, you must pass `cluster=<your clusters as integers per cell>, categories=<cell type names matching your cluster numbers>` into the [`make_example`](https://github.com/imsb-uke/scGAN/blob/151a7f2f578625ca42fc5205208fce86bcb055b1/preprocessing/write_tfrecords.py#L40C5-L41C17) function.
> 
> I assume you already modified the `main.py` and did something like this, right? Could you let me know what modifications you did already if your problem persists after the modification to the `make_example` call mentioned above?

Thank you for your prompt response. It's my fault. I reviewed the code and data once again today and found that although adata.obs['cluster'] is of pandas category type, its category label data type is an integer rather than a string object. This causes the condition "if cluster" in the make_example function to not trigger when the cluster number is 0, leading to the aforementioned error message. I believe it would be better to change this to "if cluster is not None". After making this change, the model can be trained normally.

**Comment by fhausmann** [comment]
> Thank you for your prompt response. It's my fault. I reviewed the code and data once again today and found that although adata.obs['cluster'] is of pandas category type, its category label data type is an integer rather than a string object. This causes the condition "if cluster" in the make_example function to not trigger when the cluster number is 0, leading to the aforementioned error message. I believe it would be better to change this to "if cluster is not None". After making this change, the model can be trained normally.

Thank you, you're right. I changed that.
